package com.kaishengit.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Wed Nov 01 11:11:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbg.generated Wed Nov 01 11:11:08 CST 2017
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_age
     *
     * @mbg.generated Wed Nov 01 11:11:08 CST 2017
     */
    private Integer stuAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Wed Nov 01 11:11:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Wed Nov 01 11:11:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbg.generated Wed Nov 01 11:11:08 CST 2017
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbg.generated Wed Nov 01 11:11:08 CST 2017
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_age
     *
     * @return the value of student.stu_age
     *
     * @mbg.generated Wed Nov 01 11:11:08 CST 2017
     */
    public Integer getStuAge() {
        return stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_age
     *
     * @param stuAge the value for student.stu_age
     *
     * @mbg.generated Wed Nov 01 11:11:08 CST 2017
     */
    public void setStuAge(Integer stuAge) {
        this.stuAge = stuAge;
    }
}